<?xml version="1.0" encoding="utf-8"?><Database Name="GrafoWebService" Class="GrafoLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ANDRE-PC\SQLEXPRESS;Initial Catalog=GrafoWebService;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GrafoWebServiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_Aresta" Member="tb_Arestas">
    <Type Name="tb_Aresta">
      <Column Name="id_aresta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_origem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_destino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_Vertice_tb_Aresta" Member="tb_Vertice" ThisKey="id_destino" OtherKey="id_vertice" Type="tb_Vertice" IsForeignKey="true" />
      <Association Name="tb_Vertice_tb_Aresta1" Member="tb_Vertice1" ThisKey="id_origem" OtherKey="id_vertice" Type="tb_Vertice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Grafo" Member="tb_Grafos">
    <Type Name="tb_Grafo">
      <Column Name="id_grafo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_Grafo_tb_Vertice" Member="tb_Vertices" ThisKey="id_grafo" OtherKey="id_grafo" Type="tb_Vertice" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Vertice" Member="tb_Vertices">
    <Type Name="tb_Vertice">
      <Column Name="id_vertice" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_grafo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="posX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="posY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="tb_Vertice_tb_Aresta" Member="tb_Arestas" ThisKey="id_vertice" OtherKey="id_destino" Type="tb_Aresta" />
      <Association Name="tb_Vertice_tb_Aresta1" Member="tb_Arestas1" ThisKey="id_vertice" OtherKey="id_origem" Type="tb_Aresta" />
      <Association Name="tb_Grafo_tb_Vertice" Member="tb_Grafo" ThisKey="id_grafo" OtherKey="id_grafo" Type="tb_Grafo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>