#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrafoWebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GrafoWebService")]
	public partial class GrafoLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_Aresta(tb_Aresta instance);
    partial void Updatetb_Aresta(tb_Aresta instance);
    partial void Deletetb_Aresta(tb_Aresta instance);
    partial void Inserttb_Grafo(tb_Grafo instance);
    partial void Updatetb_Grafo(tb_Grafo instance);
    partial void Deletetb_Grafo(tb_Grafo instance);
    partial void Inserttb_Vertice(tb_Vertice instance);
    partial void Updatetb_Vertice(tb_Vertice instance);
    partial void Deletetb_Vertice(tb_Vertice instance);
    #endregion
		
		public GrafoLinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GrafoWebServiceConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GrafoLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GrafoLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GrafoLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GrafoLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_Aresta> tb_Arestas
		{
			get
			{
				return this.GetTable<tb_Aresta>();
			}
		}
		
		public System.Data.Linq.Table<tb_Grafo> tb_Grafos
		{
			get
			{
				return this.GetTable<tb_Grafo>();
			}
		}
		
		public System.Data.Linq.Table<tb_Vertice> tb_Vertices
		{
			get
			{
				return this.GetTable<tb_Vertice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Aresta")]
	public partial class tb_Aresta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_aresta;
		
		private int _id_origem;
		
		private int _id_destino;
		
		private int _peso;
		
		private EntityRef<tb_Vertice> _tb_Vertice;
		
		private EntityRef<tb_Vertice> _tb_Vertice1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_arestaChanging(int value);
    partial void Onid_arestaChanged();
    partial void Onid_origemChanging(int value);
    partial void Onid_origemChanged();
    partial void Onid_destinoChanging(int value);
    partial void Onid_destinoChanged();
    partial void OnpesoChanging(int value);
    partial void OnpesoChanged();
    #endregion
		
		public tb_Aresta()
		{
			this._tb_Vertice = default(EntityRef<tb_Vertice>);
			this._tb_Vertice1 = default(EntityRef<tb_Vertice>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_aresta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_aresta
		{
			get
			{
				return this._id_aresta;
			}
			set
			{
				if ((this._id_aresta != value))
				{
					this.Onid_arestaChanging(value);
					this.SendPropertyChanging();
					this._id_aresta = value;
					this.SendPropertyChanged("id_aresta");
					this.Onid_arestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_origem", DbType="Int NOT NULL")]
		public int id_origem
		{
			get
			{
				return this._id_origem;
			}
			set
			{
				if ((this._id_origem != value))
				{
					if (this._tb_Vertice1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_origemChanging(value);
					this.SendPropertyChanging();
					this._id_origem = value;
					this.SendPropertyChanged("id_origem");
					this.Onid_origemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_destino", DbType="Int NOT NULL")]
		public int id_destino
		{
			get
			{
				return this._id_destino;
			}
			set
			{
				if ((this._id_destino != value))
				{
					if (this._tb_Vertice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_destinoChanging(value);
					this.SendPropertyChanging();
					this._id_destino = value;
					this.SendPropertyChanged("id_destino");
					this.Onid_destinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Int NOT NULL")]
		public int peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this.OnpesoChanging(value);
					this.SendPropertyChanging();
					this._peso = value;
					this.SendPropertyChanged("peso");
					this.OnpesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Vertice_tb_Aresta", Storage="_tb_Vertice", ThisKey="id_destino", OtherKey="id_vertice", IsForeignKey=true)]
		public tb_Vertice tb_Vertice
		{
			get
			{
				return this._tb_Vertice.Entity;
			}
			set
			{
				tb_Vertice previousValue = this._tb_Vertice.Entity;
				if (((previousValue != value) 
							|| (this._tb_Vertice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Vertice.Entity = null;
						previousValue.tb_Arestas.Remove(this);
					}
					this._tb_Vertice.Entity = value;
					if ((value != null))
					{
						value.tb_Arestas.Add(this);
						this._id_destino = value.id_vertice;
					}
					else
					{
						this._id_destino = default(int);
					}
					this.SendPropertyChanged("tb_Vertice");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Vertice_tb_Aresta1", Storage="_tb_Vertice1", ThisKey="id_origem", OtherKey="id_vertice", IsForeignKey=true)]
		public tb_Vertice tb_Vertice1
		{
			get
			{
				return this._tb_Vertice1.Entity;
			}
			set
			{
				tb_Vertice previousValue = this._tb_Vertice1.Entity;
				if (((previousValue != value) 
							|| (this._tb_Vertice1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Vertice1.Entity = null;
						previousValue.tb_Arestas1.Remove(this);
					}
					this._tb_Vertice1.Entity = value;
					if ((value != null))
					{
						value.tb_Arestas1.Add(this);
						this._id_origem = value.id_vertice;
					}
					else
					{
						this._id_origem = default(int);
					}
					this.SendPropertyChanged("tb_Vertice1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Grafo")]
	public partial class tb_Grafo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_grafo;
		
		private string _nome;
		
		private int _width;
		
		private int _height;
		
		private EntitySet<tb_Vertice> _tb_Vertices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_grafoChanging(int value);
    partial void Onid_grafoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnwidthChanging(int value);
    partial void OnwidthChanged();
    partial void OnheightChanging(int value);
    partial void OnheightChanged();
    #endregion
		
		public tb_Grafo()
		{
			this._tb_Vertices = new EntitySet<tb_Vertice>(new Action<tb_Vertice>(this.attach_tb_Vertices), new Action<tb_Vertice>(this.detach_tb_Vertices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grafo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_grafo
		{
			get
			{
				return this._id_grafo;
			}
			set
			{
				if ((this._id_grafo != value))
				{
					this.Onid_grafoChanging(value);
					this.SendPropertyChanging();
					this._id_grafo = value;
					this.SendPropertyChanged("id_grafo");
					this.Onid_grafoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width", DbType="Int NOT NULL")]
		public int width
		{
			get
			{
				return this._width;
			}
			set
			{
				if ((this._width != value))
				{
					this.OnwidthChanging(value);
					this.SendPropertyChanging();
					this._width = value;
					this.SendPropertyChanged("width");
					this.OnwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int NOT NULL")]
		public int height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Grafo_tb_Vertice", Storage="_tb_Vertices", ThisKey="id_grafo", OtherKey="id_grafo")]
		public EntitySet<tb_Vertice> tb_Vertices
		{
			get
			{
				return this._tb_Vertices;
			}
			set
			{
				this._tb_Vertices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Vertices(tb_Vertice entity)
		{
			this.SendPropertyChanging();
			entity.tb_Grafo = this;
		}
		
		private void detach_tb_Vertices(tb_Vertice entity)
		{
			this.SendPropertyChanging();
			entity.tb_Grafo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Vertice")]
	public partial class tb_Vertice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vertice;
		
		private int _id_grafo;
		
		private int _posX;
		
		private int _posY;
		
		private string _nome;
		
		private EntitySet<tb_Aresta> _tb_Arestas;
		
		private EntitySet<tb_Aresta> _tb_Arestas1;
		
		private EntityRef<tb_Grafo> _tb_Grafo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_verticeChanging(int value);
    partial void Onid_verticeChanged();
    partial void Onid_grafoChanging(int value);
    partial void Onid_grafoChanged();
    partial void OnposXChanging(int value);
    partial void OnposXChanged();
    partial void OnposYChanging(int value);
    partial void OnposYChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    #endregion
		
		public tb_Vertice()
		{
			this._tb_Arestas = new EntitySet<tb_Aresta>(new Action<tb_Aresta>(this.attach_tb_Arestas), new Action<tb_Aresta>(this.detach_tb_Arestas));
			this._tb_Arestas1 = new EntitySet<tb_Aresta>(new Action<tb_Aresta>(this.attach_tb_Arestas1), new Action<tb_Aresta>(this.detach_tb_Arestas1));
			this._tb_Grafo = default(EntityRef<tb_Grafo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vertice", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vertice
		{
			get
			{
				return this._id_vertice;
			}
			set
			{
				if ((this._id_vertice != value))
				{
					this.Onid_verticeChanging(value);
					this.SendPropertyChanging();
					this._id_vertice = value;
					this.SendPropertyChanged("id_vertice");
					this.Onid_verticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grafo", DbType="Int NOT NULL")]
		public int id_grafo
		{
			get
			{
				return this._id_grafo;
			}
			set
			{
				if ((this._id_grafo != value))
				{
					if (this._tb_Grafo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_grafoChanging(value);
					this.SendPropertyChanging();
					this._id_grafo = value;
					this.SendPropertyChanged("id_grafo");
					this.Onid_grafoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posX", DbType="Int NOT NULL")]
		public int posX
		{
			get
			{
				return this._posX;
			}
			set
			{
				if ((this._posX != value))
				{
					this.OnposXChanging(value);
					this.SendPropertyChanging();
					this._posX = value;
					this.SendPropertyChanged("posX");
					this.OnposXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posY", DbType="Int NOT NULL")]
		public int posY
		{
			get
			{
				return this._posY;
			}
			set
			{
				if ((this._posY != value))
				{
					this.OnposYChanging(value);
					this.SendPropertyChanging();
					this._posY = value;
					this.SendPropertyChanged("posY");
					this.OnposYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Vertice_tb_Aresta", Storage="_tb_Arestas", ThisKey="id_vertice", OtherKey="id_destino")]
		public EntitySet<tb_Aresta> tb_Arestas
		{
			get
			{
				return this._tb_Arestas;
			}
			set
			{
				this._tb_Arestas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Vertice_tb_Aresta1", Storage="_tb_Arestas1", ThisKey="id_vertice", OtherKey="id_origem")]
		public EntitySet<tb_Aresta> tb_Arestas1
		{
			get
			{
				return this._tb_Arestas1;
			}
			set
			{
				this._tb_Arestas1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Grafo_tb_Vertice", Storage="_tb_Grafo", ThisKey="id_grafo", OtherKey="id_grafo", IsForeignKey=true)]
		public tb_Grafo tb_Grafo
		{
			get
			{
				return this._tb_Grafo.Entity;
			}
			set
			{
				tb_Grafo previousValue = this._tb_Grafo.Entity;
				if (((previousValue != value) 
							|| (this._tb_Grafo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Grafo.Entity = null;
						previousValue.tb_Vertices.Remove(this);
					}
					this._tb_Grafo.Entity = value;
					if ((value != null))
					{
						value.tb_Vertices.Add(this);
						this._id_grafo = value.id_grafo;
					}
					else
					{
						this._id_grafo = default(int);
					}
					this.SendPropertyChanged("tb_Grafo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Arestas(tb_Aresta entity)
		{
			this.SendPropertyChanging();
			entity.tb_Vertice = this;
		}
		
		private void detach_tb_Arestas(tb_Aresta entity)
		{
			this.SendPropertyChanging();
			entity.tb_Vertice = null;
		}
		
		private void attach_tb_Arestas1(tb_Aresta entity)
		{
			this.SendPropertyChanging();
			entity.tb_Vertice1 = this;
		}
		
		private void detach_tb_Arestas1(tb_Aresta entity)
		{
			this.SendPropertyChanging();
			entity.tb_Vertice1 = null;
		}
	}
}
#pragma warning restore 1591
